Repository Team-Clmap/clmap, pull requests merged in 2024-12, with the labels that each got.

#1 CM-175: 📘 커밋 메세지 템플릿 추가
  .gitmessage.txt
  README.md
Labels: docs

#3 CM-175: 📘 PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
Labels: docs

#5 CM-170: 📦 프로젝트 기본 환경설정
  .gitignore
  README.md
  app/api/auth/[...nextauth].ts
  app/layout.tsx
  app/page.tsx
  next-env.d.ts
  next.config.ts
  package.json
  public/favicon.ico
  public/icons/icon-192x192.png
  public/icons/icon-512x512.png
  public/manifest.json
  public/sw.js
  public/workbox-bd7e3b9b.js
  styles/global.css
  tsconfig.json
  utils/react-query-client.ts
  yarn.lock
Labels: chore

#6 CM-171: 📦 백엔드 환경 설정 (DB, swagger)
  .github/auto-assign.yml
  app/api-doc/page.tsx
  app/api-doc/react-swagger.tsx
  app/api/test/checkConnection.ts
  app/api/test/route.ts
  package.json
  tsconfig.json
  utils/db.ts
  utils/swagger.ts
  yarn.lock
Labels: chore

#10 CM-103: ✨ Header 제작
  app/visit/[id]/page.tsx
  app/visit/page.tsx
  components/Header.tsx
  public/icons/arrow-left.png
  styles/global.css
Labels: feat

#8 CM-99: ✨ TabBar 제작
  app/map/page.tsx
  app/profile/page.tsx
  app/record/page.tsx
  app/review/page.tsx
  app/timer/page.tsx
  app/visit/page.tsx
  components/TabBar.tsx
  public/icons/lens-blue.png
  public/icons/lens.png
  public/icons/logo-192x192.png
  public/icons/logo-512x512.png
  public/icons/map-blue.png
  public/icons/map.png
  public/icons/mountain-blue.png
  public/icons/mountain.png
  public/icons/profile-blue.png
  public/icons/profile.png
  public/icons/watch-blue.png
  public/icons/watch.png
  public/icons/write-blue.png
  public/icons/write.png
  public/manifest.json
Labels: feat

#7 CM-98: ✨ BottomSheet 제작
  app/layout.tsx
  components/BottomSheet.tsx
  public/fonts/NanumSquareB.ttf
  public/fonts/NanumSquareEB.ttf
  public/fonts/NanumSquareL.ttf
  public/fonts/NanumSquareR.ttf
  styles/global.css
Labels: feat

#11 CM-107: ✨ Input & GradeInput 제작
  app/page.tsx
  components/GradeInput.tsx
  components/Input.tsx
Labels: feat

#12 CM-108: ✨ 라디오 버튼 제작
  app/layout.tsx
  app/page.tsx
  components/RadioButton.tsx
  styles/global.css
Labels: feat

#13 CM-109: ✨ SearchField 제작
  app/page.tsx
  components/Header.tsx
  components/SearchField.tsx
  public/icons/search.png
Labels: feat

#14 CM-121: ✨ DatePicker, Calendar 제작 및 기존 컴포 리팩토링
  app/page.tsx
  components/Calendar.tsx
  components/DatePicker.tsx
  components/Popup.tsx
  components/Scrim.tsx
  public/icons/arrow-left-blue.png
  public/icons/arrow-right-blue.png
  public/icons/calendar.png
Labels: feat
